package persistent

import (
	"context"
	"fmt"

	"github.com/minhhoccode111/todo-list/internal/entity"
	"github.com/minhhoccode111/todo-list/internal/repo/persistent/sqlc"
	"github.com/minhhoccode111/todo-list/pkg/postgres"
)

// TranslationRepo -.
// This layer acts as an Adapter between the database and business logic.
// It maps database-specific structures (generated by sqlc) to core business entities.
type TranslationRepo struct {
	*postgres.Postgres
	queries *sqlc.Queries
}

// NewTranslationRepo -.
func NewTranslationRepo(pg *postgres.Postgres) *TranslationRepo {
	return &TranslationRepo{
		Postgres: pg,
		queries:  sqlc.New(pg.Pool),
	}
}

// GetHistory -.
func (r *TranslationRepo) ReadHistory(ctx context.Context) ([]entity.Translation, error) {
	rows, err := r.queries.ReadHistory(ctx)
	if err != nil {
		return nil, fmt.Errorf("TranslationRepo - GetHistory - r.queries.GetHistory: %w", err)
	}

	entities := make([]entity.Translation, 0, len(rows))

	for _, row := range rows {
		entities = append(entities, entity.Translation{
			Source:      row.Source,
			Destination: row.Destination,
			Original:    row.Original,
			Translation: row.Translation,
		})
	}

	return entities, nil
}

// Store -.
// An example of a transactional store with sqlc.
func (r *TranslationRepo) CreateHistory(ctx context.Context, t entity.Translation) error {
	tx, err := r.Pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("TranslationRepo - Store - r.Pool.Begin: %w", err)
	}

	defer tx.Rollback(ctx) //nolint:errcheck // standard practice to ignore this

	queriesTx := r.queries.WithTx(tx)

	err = queriesTx.CreateHistory(ctx, sqlc.CreateHistoryParams{
		Source:      t.Source,
		Destination: t.Destination,
		Original:    t.Original,
		Translation: t.Translation,
	})
	if err != nil {
		return fmt.Errorf("TranslationRepo - Store - qtx.Store: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("TranslationRepo - Store - tx.Commit: %w", err)
	}

	return nil
}
