version: "3.9"

x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "user"


x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: "1"
  # App
  APP_NAME: "go-clean-template-gin"
  APP_VERSION: "1.0.0"
  # Cache
  CACHE_MAX_COST: "10000"
  CACHE_TTL: "5m"
  # CORS
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_ALLOW_HEADERS: "Origin,X-Requested-With,Content-Type,Accept,Authorization"
  CORS_ALLOW_METHODS: "GET,POST,HEAD,PUT,DELETE,PATCH"
  CORS_ALLOW_ORIGINS: "http://localhost:3000,https://example.com"
  # HTTP settings
  HTTP_PORT: "8080"
  # Logger
  LOG_LEVEL: "debug"
  # Metrics
  METRICS_ENABLED: "true"
  # PG
  PG_POOL_MAX: "2"
  PG_URL: "postgres://user:password@db:5432/db"
  # Swagger
  SWAGGER_ENABLED: "true"

services:
  db:
    container_name: db
    image: postgres:18.3-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      app_network:
        aliases:
          - db.lvh.me



  app:
    container_name: app
    platform: linux/amd64
    pid: "host"
    build:
      context: .
    environment:
      <<: *x-backend-app-environment
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "2Gb"
        reservations:
          cpus: "0.60"
          memory: "1Gb"
    networks:
      app_network:
        aliases:
          - app.lvh.me

  nginx:
    container_name: nginx
    image: nginx:1.29.6-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      app_network:
        aliases:
          - nginx.lvh.me

networks:
  app_network:
    external: false

volumes:
  db_data:
