// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type History struct {
	ID          int32
	Source      string
	Destination string
	Original    string
	Translation string
}
