// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type PriorityLevel string

const (
	PriorityLevelLow  PriorityLevel = "low"
	PriorityLevelMed  PriorityLevel = "med"
	PriorityLevelHigh PriorityLevel = "high"
)

func (e *PriorityLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PriorityLevel(s)
	case string:
		*e = PriorityLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for PriorityLevel: %T", src)
	}
	return nil
}

type NullPriorityLevel struct {
	PriorityLevel PriorityLevel
	Valid         bool // Valid is true if PriorityLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriorityLevel) Scan(value interface{}) error {
	if value == nil {
		ns.PriorityLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PriorityLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriorityLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PriorityLevel), nil
}

type History struct {
	ID          int32
	Source      string
	Destination string
	Original    string
	Translation string
}

type Todo struct {
	ID          int32
	UserID      int32
	Title       string
	Description string
	Completed   bool
	Priority    PriorityLevel
	DueDate     pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type User struct {
	ID           int32
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
