// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateHistory(ctx context.Context, arg CreateHistoryParams) error
	CreateTodo(ctx context.Context, arg CreateTodoParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	ReadHistory(ctx context.Context) ([]ReadHistoryRow, error)
	ReadTodos(ctx context.Context, arg ReadTodosParams) ([]ReadTodosRow, error)
	ReadUserByEmail(ctx context.Context, email string) (User, error)
	ReadUserByID(ctx context.Context, id int32) (User, error)
}

var _ Querier = (*Queries)(nil)
