// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (user_id, title, description, priority, due_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, description, completed, priority, due_date, created_at, updated_at, deleted_at
`

type CreateTodoParams struct {
	UserID      int32
	Title       string
	Description string
	Priority    PriorityLevel
	DueDate     pgtype.Timestamptz
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
UPDATE todos
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type DeleteTodoParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.Exec(ctx, deleteTodo, arg.ID, arg.UserID)
	return err
}

const readTodos = `-- name: ReadTodos :many
SELECT id, user_id, title, description, completed, priority, due_date, created_at, updated_at,
    COUNT(*) OVER() as total_count
FROM todos t
WHERE deleted_at IS NULL
AND t.user_id = $1
ORDER BY updated_at DESC
LIMIT $2
OFFSET $3
`

type ReadTodosParams struct {
	UserID int32
	Limit  int32
	Offset int32
}

type ReadTodosRow struct {
	ID          int32
	UserID      int32
	Title       string
	Description string
	Completed   bool
	Priority    PriorityLevel
	DueDate     pgtype.Timestamptz
	CreatedAt   time.Time
	UpdatedAt   time.Time
	TotalCount  int64
}

func (q *Queries) ReadTodos(ctx context.Context, arg ReadTodosParams) ([]ReadTodosRow, error) {
	rows, err := q.db.Query(ctx, readTodos, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadTodosRow{}
	for rows.Next() {
		var i ReadTodosRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $2, description = $3, completed = $4, priority = $5, due_date = $6, updated_at = NOW()
WHERE id = $1 AND user_id = $7 AND deleted_at IS NULL
RETURNING id, user_id, title, description, completed, priority, due_date, created_at, updated_at, deleted_at
`

type UpdateTodoParams struct {
	ID          int32
	Title       string
	Description string
	Completed   bool
	Priority    PriorityLevel
	DueDate     pgtype.Timestamptz
	UserID      int32
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.Priority,
		arg.DueDate,
		arg.UserID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
