// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo.sql

package sqlc

import (
	"context"
	"time"
)

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (user_id, title, description, priority, due_date)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTodoParams struct {
	UserID      int32
	Title       string
	Description string
	Priority    NullPriorityLevel
	DueDate     time.Time
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.Exec(ctx, createTodo,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
	)
	return err
}

const readTodos = `-- name: ReadTodos :many
SELECT id, user_id, title, description, completed, priority, due_date, created_at, updated_at
FROM todos t
WHERE deleted_at IS NOT NULL
AND t.user_id = $1
LIMIT $2
OFFSET $3
`

type ReadTodosParams struct {
	UserID int32
	Limit  int32
	Offset int32
}

type ReadTodosRow struct {
	ID          int32
	UserID      int32
	Title       string
	Description string
	Completed   bool
	Priority    NullPriorityLevel
	DueDate     time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ReadTodos(ctx context.Context, arg ReadTodosParams) ([]ReadTodosRow, error) {
	rows, err := q.db.Query(ctx, readTodos, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadTodosRow
	for rows.Next() {
		var i ReadTodosRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
