// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package sqlc

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
insert into refresh_tokens (user_id, token_hash, expires_at, device_info)
values ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	UserID     int32
	TokenHash  string
	ExpiresAt  time.Time
	DeviceInfo string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.DeviceInfo,
	)
	return err
}

const deleteAllRefreshTokens = `-- name: DeleteAllRefreshTokens :exec
delete from refresh_tokens
where user_id = $1
`

func (q *Queries) DeleteAllRefreshTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteAllRefreshTokens, userID)
	return err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
delete from refresh_tokens
where user_id = $1 and token_hash = $2
`

type DeleteRefreshTokenByHashParams struct {
	UserID    int32
	TokenHash string
}

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, arg DeleteRefreshTokenByHashParams) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, arg.UserID, arg.TokenHash)
	return err
}

const deleteRefreshTokenById = `-- name: DeleteRefreshTokenById :exec
delete from refresh_tokens
where user_id = $1 and id = $2
`

type DeleteRefreshTokenByIdParams struct {
	UserID int32
	ID     int32
}

func (q *Queries) DeleteRefreshTokenById(ctx context.Context, arg DeleteRefreshTokenByIdParams) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenById, arg.UserID, arg.ID)
	return err
}

const readRefreshToken = `-- name: ReadRefreshToken :one
select user_id
from refresh_tokens
where token_hash = $1 and expires_at < now()
`

func (q *Queries) ReadRefreshToken(ctx context.Context, tokenHash string) (int32, error) {
	row := q.db.QueryRow(ctx, readRefreshToken, tokenHash)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}
