// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package sqlc

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
insert into refresh_tokens (user_id, token_hash, expires_at, device_info)
values ($1, $2, $3, $4)
`

type CreateRefreshTokenParams struct {
	UserID     int32
	TokenHash  string
	ExpiresAt  time.Time
	DeviceInfo string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.DeviceInfo,
	)
	return err
}

const deleteAllRefreshTokens = `-- name: DeleteAllRefreshTokens :exec
delete from refresh_tokens
where user_id = $1
`

func (q *Queries) DeleteAllRefreshTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteAllRefreshTokens, userID)
	return err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
delete from refresh_tokens
where user_id = $1 and token_hash = $2
`

type DeleteRefreshTokenByHashParams struct {
	UserID    int32
	TokenHash string
}

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, arg DeleteRefreshTokenByHashParams) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, arg.UserID, arg.TokenHash)
	return err
}

const deleteRefreshTokenByID = `-- name: DeleteRefreshTokenByID :exec
delete from refresh_tokens
where user_id = $1 and id = $2
`

type DeleteRefreshTokenByIDParams struct {
	UserID int32
	ID     int32
}

func (q *Queries) DeleteRefreshTokenByID(ctx context.Context, arg DeleteRefreshTokenByIDParams) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByID, arg.UserID, arg.ID)
	return err
}

const listRefreshTokens = `-- name: ListRefreshTokens :many
select id, device_info, created_at, expires_at, token_hash
from refresh_tokens
where user_id = $1
`

type ListRefreshTokensRow struct {
	ID         int32
	DeviceInfo string
	CreatedAt  time.Time
	ExpiresAt  time.Time
	TokenHash  string
}

func (q *Queries) ListRefreshTokens(ctx context.Context, userID int32) ([]ListRefreshTokensRow, error) {
	rows, err := q.db.Query(ctx, listRefreshTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRefreshTokensRow{}
	for rows.Next() {
		var i ListRefreshTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceInfo,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.TokenHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readRefreshToken = `-- name: ReadRefreshToken :one
delete from refresh_tokens
where token_hash = $1 and expires_at > now()
returning user_id
`

func (q *Queries) ReadRefreshToken(ctx context.Context, tokenHash string) (int32, error) {
	row := q.db.QueryRow(ctx, readRefreshToken, tokenHash)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}
