// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translation.sql

package sqlc

import (
	"context"
)

const getHistory = `-- name: GetHistory :many
SELECT source, destination, original, translation FROM history
`

type GetHistoryRow struct {
	Source      string
	Destination string
	Original    string
	Translation string
}

func (q *Queries) GetHistory(ctx context.Context) ([]GetHistoryRow, error) {
	rows, err := q.db.Query(ctx, getHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHistoryRow
	for rows.Next() {
		var i GetHistoryRow
		if err := rows.Scan(
			&i.Source,
			&i.Destination,
			&i.Original,
			&i.Translation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const store = `-- name: Store :exec
INSERT INTO history (source, destination, original, translation)
VALUES ($1, $2, $3, $4)
`

type StoreParams struct {
	Source      string
	Destination string
	Original    string
	Translation string
}

func (q *Queries) Store(ctx context.Context, arg StoreParams) error {
	_, err := q.db.Exec(ctx, store,
		arg.Source,
		arg.Destination,
		arg.Original,
		arg.Translation,
	)
	return err
}
