// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translation.sql

package sqlc

import (
	"context"
)

const createHistory = `-- name: CreateHistory :exec
INSERT INTO history (source, destination, original, translation)
VALUES ($1, $2, $3, $4)
`

type CreateHistoryParams struct {
	Source      string
	Destination string
	Original    string
	Translation string
}

func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) error {
	_, err := q.db.Exec(ctx, createHistory,
		arg.Source,
		arg.Destination,
		arg.Original,
		arg.Translation,
	)
	return err
}

const readHistory = `-- name: ReadHistory :many
SELECT source, destination, original, translation FROM history
`

type ReadHistoryRow struct {
	Source      string
	Destination string
	Original    string
	Translation string
}

func (q *Queries) ReadHistory(ctx context.Context) ([]ReadHistoryRow, error) {
	rows, err := q.db.Query(ctx, readHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadHistoryRow{}
	for rows.Next() {
		var i ReadHistoryRow
		if err := rows.Scan(
			&i.Source,
			&i.Destination,
			&i.Original,
			&i.Translation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
