// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	return err
}

const readUser = `-- name: ReadUser :one
SELECT id, email, name, password_hash, created_at, updated_at
FROM users
`

func (q *Queries) ReadUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, readUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
