// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/minhhoccode111/todo-list/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// CreateHistory mocks base method.
func (m *MockTranslationRepo) CreateHistory(arg0 context.Context, arg1 entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHistory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateHistory indicates an expected call of CreateHistory.
func (mr *MockTranslationRepoMockRecorder) CreateHistory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHistory", reflect.TypeOf((*MockTranslationRepo)(nil).CreateHistory), arg0, arg1)
}

// ReadHistory mocks base method.
func (m *MockTranslationRepo) ReadHistory(arg0 context.Context) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadHistory", arg0)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadHistory indicates an expected call of ReadHistory.
func (mr *MockTranslationRepoMockRecorder) ReadHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadHistory", reflect.TypeOf((*MockTranslationRepo)(nil).ReadHistory), arg0)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(arg0 entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), arg0)
}

// MockTranslationCache is a mock of TranslationCache interface.
type MockTranslationCache struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationCacheMockRecorder
	isgomock struct{}
}

// MockTranslationCacheMockRecorder is the mock recorder for MockTranslationCache.
type MockTranslationCacheMockRecorder struct {
	mock *MockTranslationCache
}

// NewMockTranslationCache creates a new mock instance.
func NewMockTranslationCache(ctrl *gomock.Controller) *MockTranslationCache {
	mock := &MockTranslationCache{ctrl: ctrl}
	mock.recorder = &MockTranslationCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationCache) EXPECT() *MockTranslationCacheMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationCache) GetHistory(ctx context.Context) ([]entity.Translation, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationCacheMockRecorder) GetHistory(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationCache)(nil).GetHistory), ctx)
}

// InvalidateHistory mocks base method.
func (m *MockTranslationCache) InvalidateHistory(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateHistory", ctx)
}

// InvalidateHistory indicates an expected call of InvalidateHistory.
func (mr *MockTranslationCacheMockRecorder) InvalidateHistory(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateHistory", reflect.TypeOf((*MockTranslationCache)(nil).InvalidateHistory), ctx)
}

// SetHistory mocks base method.
func (m *MockTranslationCache) SetHistory(ctx context.Context, history []entity.Translation) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHistory", ctx, history)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetHistory indicates an expected call of SetHistory.
func (mr *MockTranslationCacheMockRecorder) SetHistory(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHistory", reflect.TypeOf((*MockTranslationCache)(nil).SetHistory), ctx, history)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *MockUserRepo) CreateRefreshToken(arg0 context.Context, arg1 int32, arg2, arg3 string, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockUserRepoMockRecorder) CreateRefreshToken(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockUserRepo)(nil).CreateRefreshToken), arg0, arg1, arg2, arg3, arg4)
}

// CreateUser mocks base method.
func (m *MockUserRepo) CreateUser(arg0 context.Context, arg1 *entity.User) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepoMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepo)(nil).CreateUser), arg0, arg1)
}

// DeleteExpiredRefreshTokens mocks base method.
func (m *MockUserRepo) DeleteExpiredRefreshTokens(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredRefreshTokens", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredRefreshTokens indicates an expected call of DeleteExpiredRefreshTokens.
func (mr *MockUserRepoMockRecorder) DeleteExpiredRefreshTokens(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredRefreshTokens", reflect.TypeOf((*MockUserRepo)(nil).DeleteExpiredRefreshTokens), arg0)
}

// ReadRefreshTokenByHash mocks base method.
func (m *MockUserRepo) ReadRefreshTokenByHash(arg0 context.Context, arg1 string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRefreshTokenByHash", arg0, arg1)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRefreshTokenByHash indicates an expected call of ReadRefreshTokenByHash.
func (mr *MockUserRepoMockRecorder) ReadRefreshTokenByHash(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRefreshTokenByHash", reflect.TypeOf((*MockUserRepo)(nil).ReadRefreshTokenByHash), arg0, arg1)
}

// ReadUserByEmail mocks base method.
func (m *MockUserRepo) ReadUserByEmail(arg0 context.Context, arg1 string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUserByEmail indicates an expected call of ReadUserByEmail.
func (mr *MockUserRepoMockRecorder) ReadUserByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUserByEmail", reflect.TypeOf((*MockUserRepo)(nil).ReadUserByEmail), arg0, arg1)
}

// ReadUserByID mocks base method.
func (m *MockUserRepo) ReadUserByID(arg0 context.Context, arg1 int32) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUserByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUserByID indicates an expected call of ReadUserByID.
func (mr *MockUserRepoMockRecorder) ReadUserByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUserByID", reflect.TypeOf((*MockUserRepo)(nil).ReadUserByID), arg0, arg1)
}

// RevokeAllUserRefreshTokens mocks base method.
func (m *MockUserRepo) RevokeAllUserRefreshTokens(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserRefreshTokens", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserRefreshTokens indicates an expected call of RevokeAllUserRefreshTokens.
func (mr *MockUserRepoMockRecorder) RevokeAllUserRefreshTokens(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserRefreshTokens", reflect.TypeOf((*MockUserRepo)(nil).RevokeAllUserRefreshTokens), arg0, arg1)
}

// RevokeRefreshToken mocks base method.
func (m *MockUserRepo) RevokeRefreshToken(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockUserRepoMockRecorder) RevokeRefreshToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockUserRepo)(nil).RevokeRefreshToken), arg0, arg1)
}

// MockUserCache is a mock of UserCache interface.
type MockUserCache struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheMockRecorder
	isgomock struct{}
}

// MockUserCacheMockRecorder is the mock recorder for MockUserCache.
type MockUserCacheMockRecorder struct {
	mock *MockUserCache
}

// NewMockUserCache creates a new mock instance.
func NewMockUserCache(ctrl *gomock.Controller) *MockUserCache {
	mock := &MockUserCache{ctrl: ctrl}
	mock.recorder = &MockUserCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCache) EXPECT() *MockUserCacheMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockUserCache) GetUser(c context.Context, userID string) (*entity.User, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", c, userID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserCacheMockRecorder) GetUser(c, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserCache)(nil).GetUser), c, userID)
}

// InvalidateUser mocks base method.
func (m *MockUserCache) InvalidateUser(c context.Context, userID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateUser", c, userID)
}

// InvalidateUser indicates an expected call of InvalidateUser.
func (mr *MockUserCacheMockRecorder) InvalidateUser(c, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUser", reflect.TypeOf((*MockUserCache)(nil).InvalidateUser), c, userID)
}

// SetUser mocks base method.
func (m *MockUserCache) SetUser(c context.Context, userID string, u *entity.User) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUser", c, userID, u)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetUser indicates an expected call of SetUser.
func (mr *MockUserCacheMockRecorder) SetUser(c, userID, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUser", reflect.TypeOf((*MockUserCache)(nil).SetUser), c, userID, u)
}

// MockTodoRepo is a mock of TodoRepo interface.
type MockTodoRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTodoRepoMockRecorder
	isgomock struct{}
}

// MockTodoRepoMockRecorder is the mock recorder for MockTodoRepo.
type MockTodoRepoMockRecorder struct {
	mock *MockTodoRepo
}

// NewMockTodoRepo creates a new mock instance.
func NewMockTodoRepo(ctrl *gomock.Controller) *MockTodoRepo {
	mock := &MockTodoRepo{ctrl: ctrl}
	mock.recorder = &MockTodoRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoRepo) EXPECT() *MockTodoRepoMockRecorder {
	return m.recorder
}

// CreateTodo mocks base method.
func (m *MockTodoRepo) CreateTodo(arg0 context.Context, arg1 *entity.Todo) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", arg0, arg1)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockTodoRepoMockRecorder) CreateTodo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockTodoRepo)(nil).CreateTodo), arg0, arg1)
}

// DeleteTodo mocks base method.
func (m *MockTodoRepo) DeleteTodo(arg0 context.Context, arg1, arg2 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockTodoRepoMockRecorder) DeleteTodo(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockTodoRepo)(nil).DeleteTodo), arg0, arg1, arg2)
}

// ReadTodoByID mocks base method.
func (m *MockTodoRepo) ReadTodoByID(arg0 context.Context, arg1 int32) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadTodoByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadTodoByID indicates an expected call of ReadTodoByID.
func (mr *MockTodoRepoMockRecorder) ReadTodoByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTodoByID", reflect.TypeOf((*MockTodoRepo)(nil).ReadTodoByID), arg0, arg1)
}

// ReadTodos mocks base method.
func (m *MockTodoRepo) ReadTodos(arg0 context.Context, arg1, arg2, arg3 int32) ([]entity.Todo, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadTodos", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]entity.Todo)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadTodos indicates an expected call of ReadTodos.
func (mr *MockTodoRepoMockRecorder) ReadTodos(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTodos", reflect.TypeOf((*MockTodoRepo)(nil).ReadTodos), arg0, arg1, arg2, arg3)
}

// UpdateTodo mocks base method.
func (m *MockTodoRepo) UpdateTodo(arg0 context.Context, arg1 *entity.Todo) (*entity.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", arg0, arg1)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockTodoRepoMockRecorder) UpdateTodo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockTodoRepo)(nil).UpdateTodo), arg0, arg1)
}

// MockTodoCache is a mock of TodoCache interface.
type MockTodoCache struct {
	ctrl     *gomock.Controller
	recorder *MockTodoCacheMockRecorder
	isgomock struct{}
}

// MockTodoCacheMockRecorder is the mock recorder for MockTodoCache.
type MockTodoCacheMockRecorder struct {
	mock *MockTodoCache
}

// NewMockTodoCache creates a new mock instance.
func NewMockTodoCache(ctrl *gomock.Controller) *MockTodoCache {
	mock := &MockTodoCache{ctrl: ctrl}
	mock.recorder = &MockTodoCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoCache) EXPECT() *MockTodoCacheMockRecorder {
	return m.recorder
}

// GetTodo mocks base method.
func (m *MockTodoCache) GetTodo(c context.Context, userID, todoID string) (*entity.Todo, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodo", c, userID, todoID)
	ret0, _ := ret[0].(*entity.Todo)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetTodo indicates an expected call of GetTodo.
func (mr *MockTodoCacheMockRecorder) GetTodo(c, userID, todoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodo", reflect.TypeOf((*MockTodoCache)(nil).GetTodo), c, userID, todoID)
}

// GetTodos mocks base method.
func (m *MockTodoCache) GetTodos(c context.Context, userID, limit, offset string) (*entity.Todos, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodos", c, userID, limit, offset)
	ret0, _ := ret[0].(*entity.Todos)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetTodos indicates an expected call of GetTodos.
func (mr *MockTodoCacheMockRecorder) GetTodos(c, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodos", reflect.TypeOf((*MockTodoCache)(nil).GetTodos), c, userID, limit, offset)
}

// InvalidateAllTodos mocks base method.
func (m *MockTodoCache) InvalidateAllTodos(c context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateAllTodos", c)
}

// InvalidateAllTodos indicates an expected call of InvalidateAllTodos.
func (mr *MockTodoCacheMockRecorder) InvalidateAllTodos(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAllTodos", reflect.TypeOf((*MockTodoCache)(nil).InvalidateAllTodos), c)
}

// InvalidateTodo mocks base method.
func (m *MockTodoCache) InvalidateTodo(c context.Context, userID, todoID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateTodo", c, userID, todoID)
}

// InvalidateTodo indicates an expected call of InvalidateTodo.
func (mr *MockTodoCacheMockRecorder) InvalidateTodo(c, userID, todoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateTodo", reflect.TypeOf((*MockTodoCache)(nil).InvalidateTodo), c, userID, todoID)
}

// InvalidateTodos mocks base method.
func (m *MockTodoCache) InvalidateTodos(c context.Context, userID, limit, offset string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateTodos", c, userID, limit, offset)
}

// InvalidateTodos indicates an expected call of InvalidateTodos.
func (mr *MockTodoCacheMockRecorder) InvalidateTodos(c, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateTodos", reflect.TypeOf((*MockTodoCache)(nil).InvalidateTodos), c, userID, limit, offset)
}

// SetTodo mocks base method.
func (m *MockTodoCache) SetTodo(c context.Context, userID, todoID string, t *entity.Todo) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTodo", c, userID, todoID, t)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetTodo indicates an expected call of SetTodo.
func (mr *MockTodoCacheMockRecorder) SetTodo(c, userID, todoID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTodo", reflect.TypeOf((*MockTodoCache)(nil).SetTodo), c, userID, todoID, t)
}

// SetTodos mocks base method.
func (m *MockTodoCache) SetTodos(c context.Context, userID, limit, offset string, t *entity.Todos) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTodos", c, userID, limit, offset, t)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetTodos indicates an expected call of SetTodos.
func (mr *MockTodoCacheMockRecorder) SetTodos(c, userID, limit, offset, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTodos", reflect.TypeOf((*MockTodoCache)(nil).SetTodos), c, userID, limit, offset, t)
}
