// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/minhhoccode111/todo-list/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// CreateHistory mocks base method.
func (m *MockTranslationRepo) CreateHistory(arg0 context.Context, arg1 entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHistory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateHistory indicates an expected call of CreateHistory.
func (mr *MockTranslationRepoMockRecorder) CreateHistory(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHistory", reflect.TypeOf((*MockTranslationRepo)(nil).CreateHistory), arg0, arg1)
}

// ReadHistory mocks base method.
func (m *MockTranslationRepo) ReadHistory(arg0 context.Context) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadHistory", arg0)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadHistory indicates an expected call of ReadHistory.
func (mr *MockTranslationRepoMockRecorder) ReadHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadHistory", reflect.TypeOf((*MockTranslationRepo)(nil).ReadHistory), arg0)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(arg0 entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), arg0)
}

// MockTranslationCache is a mock of TranslationCache interface.
type MockTranslationCache struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationCacheMockRecorder
	isgomock struct{}
}

// MockTranslationCacheMockRecorder is the mock recorder for MockTranslationCache.
type MockTranslationCacheMockRecorder struct {
	mock *MockTranslationCache
}

// NewMockTranslationCache creates a new mock instance.
func NewMockTranslationCache(ctrl *gomock.Controller) *MockTranslationCache {
	mock := &MockTranslationCache{ctrl: ctrl}
	mock.recorder = &MockTranslationCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationCache) EXPECT() *MockTranslationCacheMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationCache) GetHistory(ctx context.Context) ([]entity.Translation, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationCacheMockRecorder) GetHistory(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationCache)(nil).GetHistory), ctx)
}

// InvalidateHistory mocks base method.
func (m *MockTranslationCache) InvalidateHistory(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateHistory", ctx)
}

// InvalidateHistory indicates an expected call of InvalidateHistory.
func (mr *MockTranslationCacheMockRecorder) InvalidateHistory(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateHistory", reflect.TypeOf((*MockTranslationCache)(nil).InvalidateHistory), ctx)
}

// SetHistory mocks base method.
func (m *MockTranslationCache) SetHistory(ctx context.Context, history []entity.Translation) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHistory", ctx, history)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetHistory indicates an expected call of SetHistory.
func (mr *MockTranslationCacheMockRecorder) SetHistory(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHistory", reflect.TypeOf((*MockTranslationCache)(nil).SetHistory), ctx, history)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepo) CreateUser(arg0 context.Context, arg1 *entity.User) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepoMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepo)(nil).CreateUser), arg0, arg1)
}

// ReadUserByID mocks base method.
func (m *MockUserRepo) ReadUserByID(arg0 context.Context, arg1 string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUserByID", arg0, arg1)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUserByID indicates an expected call of ReadUserByID.
func (mr *MockUserRepoMockRecorder) ReadUserByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUserByID", reflect.TypeOf((*MockUserRepo)(nil).ReadUserByID), arg0, arg1)
}

// MockUserCache is a mock of UserCache interface.
type MockUserCache struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheMockRecorder
	isgomock struct{}
}

// MockUserCacheMockRecorder is the mock recorder for MockUserCache.
type MockUserCacheMockRecorder struct {
	mock *MockUserCache
}

// NewMockUserCache creates a new mock instance.
func NewMockUserCache(ctrl *gomock.Controller) *MockUserCache {
	mock := &MockUserCache{ctrl: ctrl}
	mock.recorder = &MockUserCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCache) EXPECT() *MockUserCacheMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockUserCache) GetUser(arg0 context.Context, arg1 string) (*entity.User, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserCacheMockRecorder) GetUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserCache)(nil).GetUser), arg0, arg1)
}

// InvalidateUser mocks base method.
func (m *MockUserCache) InvalidateUser(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateUser", arg0, arg1)
}

// InvalidateUser indicates an expected call of InvalidateUser.
func (mr *MockUserCacheMockRecorder) InvalidateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUser", reflect.TypeOf((*MockUserCache)(nil).InvalidateUser), arg0, arg1)
}

// SetUser mocks base method.
func (m *MockUserCache) SetUser(arg0 context.Context, arg1 string, arg2 *entity.User) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SetUser indicates an expected call of SetUser.
func (mr *MockUserCacheMockRecorder) SetUser(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUser", reflect.TypeOf((*MockUserCache)(nil).SetUser), arg0, arg1, arg2)
}
