@url = http://localhost:8080
@api = {{url}}/api/v1

@name = minhhoccode111
@email = minhhoccode111@gmail.com
@password = P@55w0rd
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiaXNzIjoidG9kby1saXN0Iiwic3ViIjoiMSIsImV4cCI6MTc4Mjc5NDEwNywiaWF0IjoxNzc0MTU0MTA3fQ.rGSpI6yn_a7Im4UGTyqDvCekxBpEzLmuyU2p2Pw26Eg

###
GET {{url}}/healthz

###
POST {{api}}/register

{
    "name": "{{name}}",
    "email": "{{email}}",
    "password": "{{password}}"
}

###
POST {{api}}/login

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
POST {{api}}/todos
Authorization: Bearer {{token}}

{
    "title": "todo-list project",
    "description": "finish todo-list project with gin-clean-arch and svelte/kit"
}
