@url = http://localhost:8080
@api = {{url}}/api/v1

@name = minhhoccode111
@email = minhhoccode111@gmail.com
@password = P@55w0rd
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxIiwiaXNzIjoidG9kby1saXN0Iiwic3ViIjoiMSIsImV4cCI6MTc4MzY4ODk0NCwiaWF0IjoxNzc1MDQ4OTQ0fQ.Nntdx_P3sjYh8vSlL1NoJSrxF6Dz0oc23FYQvqshsVU
@token0 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIyIiwiaXNzIjoidG9kby1saXN0Iiwic3ViIjoiMiIsImV4cCI6MTc4MjkxMjQwMSwiaWF0IjoxNzc0MjcyNDAxfQ.UspprUCG7p9sB-TQdDuIAMJth3r4ggKH4QMkNIMDLeo

###
GET {{url}}/healthz

###
POST {{api}}/register

{
    "name": "{{name}}",
    "email": "5-{{email}}",
    "password": "{{password}}"
}

###
POST {{api}}/login

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
POST {{api}}/refresh
Cookie: todo-list-refresh-token=7n5DjI1fuXY7nG52N2yBup4kwWIzGU0bAjpw-JNF9nQ

###
POST {{api}}/logout
Authorization: Bearer {{token}}
Cookie: todo-list-refresh-token=7n5DjI1fuXY7nG52N2yBup4kwWIzGU0bAjpw-JNF9nQ

###
POST {{api}}/logout/all
Authorization: Bearer {{token}}

###
GET {{api}}/sessions
Authorization: Bearer {{token}}
Cookie: todo-list-refresh-token=7n5DjI1fuXY7nG52N2yBup4kwWIzGU0bAjpw-JNF9nQ

###
@session_id = 1
DELETE {{api}}/sessions/{{session_id}}
Authorization: Bearer {{token}}

###
GET {{api}}/todos?page=1&limit=10
Authorization: Bearer {{token}}

###
POST {{api}}/todos
Authorization: Bearer {{token}}

{
    "title": "taivisao",
    "description": "finish this project",
    "priority": "high",
    "due_date": "2026-04-24T18:58:15.083517+07:00"
}

###
@todo_id = 1
###
PUT {{api}}/todos/{{todo_id}}
Authorization: Bearer {{token}}

{
    "title": "todo-list project",
    "description": "finish todo-list project with gin-clean-arch and svelte/kit",
    "completed": false,
    "priority": "low",
    "due_date": "2026-03-24T18:58:15.083517+07:00"
}

###
DELETE {{api}}/todos/{{todo_id}}
Authorization: Bearer {{token}}
